stages:
  - test
  - secret-detection
  - deploy

variables:
  SECRET_DETECTION_ENABLED: 'true'

secret_detection:
  stage: secret-detection

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp index.html public/
    - cp cover.png public/
    - cp *.mp3 public/
  artifacts:
    paths:
      - public
  only:
    - main